

class WidgetTemplate:
    def __init__(self):
        # Data generated by update(), accessible by ui.py and the widget
        self.data = None

    def update(self):
        """
        Called by ui.py to run CLI commands or gather data.
        Should set self.data to the latest data for this widget.
        """
        raise NotImplementedError("Each widget must implement its own update method.")

    def update_visual(self):
        """
        Called by ui.py to update the GUI for this widget.
        """
        raise NotImplementedError("Each widget must implement its own update_visual method.")